-- Auth users (replaces Supabase-hosted auth) + reading checkpoint tracking.
-- Additive only: does not touch novel / novel_chapter / comment.

CREATE TABLE IF NOT EXISTS app_user (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  name text,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reading_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  novel_id integer NOT NULL REFERENCES novel(id) ON DELETE CASCADE,
  chapter numeric NOT NULL,
  updated_at timestamp NOT NULL DEFAULT now(),
  UNIQUE (user_id, novel_id)
);
