-- Chapter comment system: logged-in users comment under their account name,
-- guests comment under a stable per-device "Anonim #N" identity (cookie-based).
-- All comments start as pending and only become visible after admin review.

CREATE TABLE IF NOT EXISTS anonymous_identity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token uuid NOT NULL UNIQUE,
  first_seen_at timestamp NOT NULL DEFAULT now(),
  last_seen_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS comment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id integer NOT NULL REFERENCES novel_chapter(id) ON DELETE CASCADE,
  user_id uuid REFERENCES app_user(id) ON DELETE SET NULL,
  anonymous_identity_id bigint REFERENCES anonymous_identity(id) ON DELETE SET NULL,
  body text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at timestamp NOT NULL DEFAULT now(),
  reviewed_at timestamp,
  reviewed_by uuid REFERENCES app_user(id) ON DELETE SET NULL,
  CONSTRAINT comment_author_check CHECK (
    (user_id IS NOT NULL)::int + (anonymous_identity_id IS NOT NULL)::int = 1
  )
);

CREATE INDEX IF NOT EXISTS comment_chapter_status_idx ON comment (chapter_id, status, created_at);
CREATE INDEX IF NOT EXISTS comment_status_idx ON comment (status, created_at);

-- Admin flag: intentionally not exposed anywhere in the app UI/API for writing.
-- Flip it directly in the database (UPDATE app_user SET is_admin = true WHERE email = '...').
ALTER TABLE app_user
  ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;
